function out1 = GKSF0_2_M_26(T)
%GKSF0_2_M_26
%    OUT1 = GKSF0_2_M_26(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-04 21:29:51

t2 = ((T < 1.9e+1./3.2e+1) & (9.0./1.6e+1 <= T));
t3 = ((T < 5.0./8.0) & (1.9e+1./3.2e+1 <= T));
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 9.0./1.6e+1)
    out1 = 0.0;
elseif (t2)
    out1 = -4.000000000000018;
elseif (t3)
    out1 = 4.000000000000018;
elseif (5.0./8.0 <= T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
