function out1 = GKSF0_2_M_37(T)
%GKSF0_2_M_37
%    OUT1 = GKSF0_2_M_37(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-04 21:29:52

t2 = ((T < 9.0./6.4e+1) & (1.0./8.0 <= T));
t3 = ((T < 5.0./3.2e+1) & (9.0./6.4e+1 <= T));
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 1.0./8.0)
    out1 = 0.0;
elseif (t2)
    out1 = -5.6568542494924;
elseif (t3)
    out1 = 5.6568542494924;
elseif (5.0./3.2e+1 <= T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
