function out1 = GKSF0_2_M_63(T)
%GKSF0_2_M_63
%    OUT1 = GKSF0_2_M_63(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-04 21:29:53

t2 = (imag(T) == 0.0);
if ~all(cellfun(@isscalar,{t2}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (t2)
    out1 = 0.0;
else
    out1 = NaN;
end
end
