function out1 = GKSF0_2_M_36(T)
%GKSF0_2_M_36
%    OUT1 = GKSF0_2_M_36(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-04 21:29:52

t2 = ((T < 7.0./6.4e+1) & (3.0./3.2e+1 <= T));
t3 = ((T < 1.0./8.0) & (7.0./6.4e+1 <= T));
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 3.0./3.2e+1)
    out1 = 0.0;
elseif (t2)
    out1 = -5.656854249492401;
elseif (t3)
    out1 = 5.656854249492401;
elseif (1.0./8.0 <= T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
