function out1 = GKSF0_2_M_1(T)
%GKSF0_2_M_1
%    OUT1 = GKSF0_2_M_1(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-04 21:29:50

t2 = ((0.0 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = 1.0;
elseif (1.0 <= T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
