function out1 = GKSF2_2_M128_7(T)
%GKSF2_2_M128_7
%    OUT1 = GKSF2_2_M128_7(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:45:34

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 5.0e-1) & (2.5e-1 <= T));
t5 = ((T < 7.5e-1) & (5.0e-1 <= T));
t6 = ((7.5e-1 <= T) & (T <= 1.0));
t7 = T.^2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*1.742403979744102e+2-t7.*9.727737906365686e+2-5.07179865627121;
elseif (t3)
    out1 = T.*-1.606203691900324e+2+t7.*3.666692780212018e+2+1.585699929150645e+1;
elseif (t4)
    out1 = T.*5.397757987427642e+1-t7.*6.252662010741579e+1-1.096774434153215e+1;
elseif (t5)
    out1 = T.*-3.478294713642443e+1+t7.*2.623390690328507e+1+1.122238741114307e+1;
elseif (t6)
    out1 = T.*3.449725003421136e+1-t7.*1.995289121047213e+1-1.475768652784536e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
