function out1 = GKSF2_2_M128_6(T)
%GKSF2_2_M128_6
%    OUT1 = GKSF2_2_M128_6(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:45:34

t2 = ((0.0 <= T) & (T < 2.5e-1));
t3 = ((T < 5.0e-1) & (2.5e-1 <= T));
t4 = ((T < 7.5e-1) & (5.0e-1 <= T));
t5 = ((7.5e-1 <= T) & (T <= 1.0));
t6 = T.^2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*1.370802423383841e+1-t6.*5.023580911302994e+1-5.427777076584636e-1;
elseif (t3)
    out1 = T.*-4.080071576921071e+1+t6.*5.87816708930683e+1+6.270814792722676;
elseif (t4)
    out1 = T.*1.110384608322094e+2-t6.*9.305750570835182e+1-3.168897935763235e+1;
elseif (t5)
    out1 = T.*-3.008258831216336e+2+t6.*1.815187235942102e+2+1.227601496250588e+2;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
