function out1 = GKSF2_2_M128_5(T)
%GKSF2_2_M128_5
%    OUT1 = GKSF2_2_M128_5(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:45:34

t2 = ((0.0 <= T) & (T < 2.5e-1));
t3 = ((T < 5.0e-1) & (2.5e-1 <= T));
t4 = ((5.0e-1 <= T) & (T <= 1.0));
t5 = T.^2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*6.185316698833791e+1-t5.*1.76043629120654e+2-3.52743525265057;
elseif (t3)
    out1 = T.*-6.415010157145921e+1+t5.*7.596290799894019e+1+1.222297331732407e+1;
elseif (t4)
    out1 = T.*3.560248603838017e+1-t5.*2.378967961089919e+1-1.271517358513578e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
