function out1 = GKSF2_2_M128_8(T)
%GKSF2_2_M128_8
%    OUT1 = GKSF2_2_M128_8(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:45:34

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 3.75e-1) & (2.5e-1 <= T));
t5 = ((3.75e-1 <= T) & (T < 5.0e-1));
t6 = ((T < 7.5e-1) & (5.0e-1 <= T));
t7 = ((7.5e-1 <= T) & (T <= 1.0));
t8 = T.^2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*4.783214034266695e+1-t8.*3.493398604047107e+2-9.489108538195651e-1;
elseif (t3)
    out1 = T.*-1.349214083711757e+2+t8.*3.816743344506599e+2+1.04731859407956e+1;
elseif (t4)
    out1 = T.*2.828479407057777e+2-t8.*4.538643637032469e+2-4.174798269382358e+1;
elseif (t5)
    out1 = T.*-3.108791069118313e+2+t8.*3.377716997868985e+2+6.957583873447812e+1;
elseif (t6)
    out1 = T.*1.066265863520254e+2-t8.*7.973399347695827e+1-3.480058458148606e+1;
elseif (t7)
    out1 = T.*-9.752307876939801e+1+t8.*5.636578327065734e+1+4.175553983904772e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
