function out1 = GKSF2_2_M128_9(T)
%GKSF2_2_M128_9
%    OUT1 = GKSF2_2_M128_9(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:45:35

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 3.75e-1) & (2.5e-1 <= T));
t5 = ((3.75e-1 <= T) & (T < 5.0e-1));
t6 = ((T < 6.25e-1) & (5.0e-1 <= T));
t7 = ((6.25e-1 <= T) & (T < 7.5e-1));
t8 = ((7.5e-1 <= T) & (T <= 1.0));
t9 = T.^2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7,t8}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*8.783703597563279-t9.*6.474940640120883e+1-1.733197899205881e-1;
elseif (t3)
    out1 = T.*-2.836459090626034e+1+t9.*8.384377161408565e+1+2.148448616568388;
elseif (t4)
    out1 = T.*9.939030871022121e+1-t9.*1.716660276188774e+2-1.382091383549181e+1;
elseif (t5)
    out1 = T.*-2.742444274514383e+2+t9.*3.265136205966685e+2+5.623559919481935e+1;
elseif (t6)
    out1 = T.*5.016481724415362e+2-t9.*4.493789792963059e+2-1.377375507784243e+2;
elseif (t7)
    out1 = T.*-5.443224307115074e+2+t9.*3.87397503226129e+2+1.891282627069019e+2;
elseif (t8)
    out1 = T.*2.644789146040405e+2-t9.*1.51803393650903e+2-1.141722417864286e+2;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
