function out1 = GKSF1_2_M128_11(T)
%GKSF1_2_M128_11
%    OUT1 = GKSF1_2_M128_11(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 6.25e-2));
t3 = ((T < 1.25e-1) & (6.25e-2 <= T));
t4 = ((T < 1.875e-1) & (1.25e-1 <= T));
t5 = ((1.875e-1 <= T) & (T < 2.5e-1));
t6 = ((T < 3.75e-1) & (2.5e-1 <= T));
t7 = ((3.75e-1 <= T) & (T < 5.0e-1));
t8 = ((T < 6.25e-1) & (5.0e-1 <= T));
t9 = ((6.25e-1 <= T) & (T < 7.5e-1));
t10 = ((7.5e-1 <= T) & (T < 8.75e-1));
t11 = ((8.75e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t10,t11,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-2.08765558510276e+1+4.349282468964083e-1;
elseif (t3)
    out1 = T.*6.26296675530828e+1-4.784210715860491;
elseif (t4)
    out1 = T.*-1.226594280783893e+2+1.837692623807352e+1;
elseif (t5)
    out1 = T.*1.070599859117314e+2-2.469546388507412e+1;
elseif (t6)
    out1 = T.*-2.09925052942533e+1+7.317658916422068;
elseif (t7)
    out1 = T.*5.624962014046856-2.663891324190491;
elseif (t8)
    out1 = T.*-1.507342761934125+9.022610637999996e-1;
elseif (t9)
    out1 = T.*4.044090336896433e-1-2.925838084648555e-1;
elseif (t10)
    out1 = T.*-1.102933728244482e-1+9.344299642071303e-2;
elseif (t11)
    out1 = T.*3.676445760814939e-2-3.523260520780983e-2;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
