function out1 = GKSF1_2_M128_7(T)
%GKSF1_2_M128_7
%    OUT1 = GKSF1_2_M128_7(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 3.75e-1) & (2.5e-1 <= T));
t5 = ((3.75e-1 <= T) & (T < 5.0e-1));
t6 = ((T < 7.5e-1) & (5.0e-1 <= T));
t7 = ((7.5e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-7.377584862137849+3.073993692557437e-1;
elseif (t3)
    out1 = T.*2.213275458641355e+1-3.381393061813181;
elseif (t4)
    out1 = T.*-4.335948997923122e+1+1.299166807959801e+1;
elseif (t5)
    out1 = T.*3.792337481765596e+1-1.748940621923468e+1;
elseif (t6)
    out1 = T.*-7.571731832194108+5.258147105690353;
elseif (t7)
    out1 = T.*2.523910610731369-2.313584726503755;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
