function out1 = GKSF1_2_M128_10(T)
%GKSF1_2_M128_10
%    OUT1 = GKSF1_2_M128_10(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 6.25e-2));
t3 = ((T < 1.25e-1) & (6.25e-2 <= T));
t4 = ((T < 2.5e-1) & (1.25e-1 <= T));
t5 = ((T < 3.75e-1) & (2.5e-1 <= T));
t6 = ((3.75e-1 <= T) & (T < 5.0e-1));
t7 = ((T < 6.25e-1) & (5.0e-1 <= T));
t8 = ((6.25e-1 <= T) & (T < 7.5e-1));
t9 = ((7.5e-1 <= T) & (T < 8.75e-1));
t10 = ((8.75e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t10,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-1.590093360837172e+2+5.246205149919535;
elseif (t3)
    out1 = T.*1.057939638014699e+2-1.130400109290466e+1;
elseif (t4)
    out1 = T.*-1.947817903357421e+1+4.355016761475854;
elseif (t5)
    out1 = T.*5.219164818475304-1.819319201536524;
elseif (t6)
    out1 = T.*-1.398480240327008+6.622976955143428e-1;
elseif (t7)
    out1 = T.*3.747561428327276e-1-2.24320496065525e-1;
elseif (t8)
    out1 = T.*-1.005443310039025e-1+7.274230008236888e-2;
elseif (t9)
    out1 = T.*2.742118118288251e-2-2.32318340577199e-2;
elseif (t10)
    out1 = T.*-9.140393727627503e-3+8.759543988976357e-3;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
