function out1 = GKSF1_2_M128_3(T)
%GKSF1_2_M128_3
%    OUT1 = GKSF1_2_M128_3(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:46

t2 = ((0.0 <= T) & (T < 5.0e-1));
t3 = ((5.0e-1 <= T) & (T <= 1.0));
t4 = T.*6.928203230275509;
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = -t4+1.732050807568877;
elseif (t3)
    out1 = t4-5.196152422706632;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
