function out1 = GKSF1_2_M128_5(T)
%GKSF1_2_M128_5
%    OUT1 = GKSF1_2_M128_5(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 2.5e-1));
t3 = ((T < 5.0e-1) & (2.5e-1 <= T));
t4 = ((T < 7.5e-1) & (5.0e-1 <= T));
t5 = ((7.5e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-2.368626101855168+1.973855084879307e-1;
elseif (t3)
    out1 = T.*7.105878305565505-2.171240593367238;
elseif (t4)
    out1 = T.*-1.500129864508273e+1+8.882347881956881;
elseif (t5)
    out1 = T.*1.973855084879307e+1-1.717253923844997e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
