function out1 = GKSF1_2_M128_8(T)
%GKSF1_2_M128_8
%    OUT1 = GKSF1_2_M128_8(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 3.75e-1) & (2.5e-1 <= T));
t5 = ((3.75e-1 <= T) & (T < 5.0e-1));
t6 = ((T < 6.25e-1) & (5.0e-1 <= T));
t7 = ((6.25e-1 <= T) & (T < 7.5e-1));
t8 = ((7.5e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7,t8}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-5.269734298217142e-1+2.195722624257142e-2;
elseif (t3)
    out1 = T.*1.580920289465143-2.415294886682857e-1;
elseif (t4)
    out1 = T.*-5.796707728038856+1.602877515707714;
elseif (t5)
    out1 = T.*2.160591062269028e+1-8.673104365815712;
elseif (t6)
    out1 = T.*-4.31942554643865e+1+2.372697867772268e+1;
elseif (t7)
    out1 = T.*3.887307333984845e+1-2.756510182492417e+1;
elseif (t8)
    out1 = T.*-9.538219079773026+8.743367489791941;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
