function out1 = GKSF1_2_M128_6(T)
%GKSF1_2_M128_6
%    OUT1 = GKSF1_2_M128_6(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 5.0e-1) & (2.5e-1 <= T));
t5 = ((T < 7.5e-1) & (5.0e-1 <= T));
t6 = ((7.5e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-5.621782671036294e+1+3.709540610070417;
elseif (t3)
    out1 = T.*3.740888840578054e+1-7.993798779447518;
elseif (t4)
    out1 = T.*-6.896610711680212+3.08257599991767;
elseif (t5)
    out1 = T.*1.88089383045824-1.306176271151555;
elseif (t6)
    out1 = T.*-6.269646101527465e-1+5.747175593066843e-1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
