function out1 = GKSF1_2_M128_9(T)
%GKSF1_2_M128_9
%    OUT1 = GKSF1_2_M128_9(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 1.25e-1));
t3 = ((T < 2.5e-1) & (1.25e-1 <= T));
t4 = ((T < 3.75e-1) & (2.5e-1 <= T));
t5 = ((3.75e-1 <= T) & (T < 5.0e-1));
t6 = ((T < 6.25e-1) & (5.0e-1 <= T));
t7 = ((6.25e-1 <= T) & (T < 7.5e-1));
t8 = ((7.5e-1 <= T) & (T < 8.75e-1));
t9 = ((8.75e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-3.455773397162374e-2+1.439905582150989e-3;
elseif (t3)
    out1 = T.*1.036732019148712e-1-1.583896140366088e-2;
elseif (t4)
    out1 = T.*-3.801350736878612e-1+1.051131074970222e-1;
elseif (t5)
    out1 = T.*1.416867092836573-5.687627049496407e-1;
elseif (t6)
    out1 = T.*-5.287333297658432+2.783337490297862;
elseif (t7)
    out1 = T.*1.973246609779716e+1-1.285403713186188e+1;
elseif (t8)
    out1 = T.*-4.23562626045535e+1+3.371250939490111e+1;
elseif (t9)
    out1 = T.*5.583377885348676e+1-5.220377688088411e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
