function out1 = GKSF1_2_M128_4(T)
%GKSF1_2_M128_4
%    OUT1 = GKSF1_2_M128_4(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 2.5e-1));
t3 = ((T < 5.0e-1) & (2.5e-1 <= T));
t4 = ((5.0e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2,t3,t4}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-1.984485277894955e+1+2.611164839335468;
elseif (t3)
    out1 = T.*1.357805716454443e+1-5.744562646538029;
elseif (t4)
    out1 = T.*-3.133397807202561+2.611164839335468;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
