function out1 = GKSF1_2_M128_12(T)
%GKSF1_2_M128_12
%    OUT1 = GKSF1_2_M128_12(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 17:41:47

t2 = ((0.0 <= T) & (T < 6.25e-2));
t3 = ((T < 1.25e-1) & (6.25e-2 <= T));
t4 = ((T < 1.875e-1) & (1.25e-1 <= T));
t5 = ((1.875e-1 <= T) & (T < 2.5e-1));
t6 = ((T < 3.125e-1) & (2.5e-1 <= T));
t7 = ((3.125e-1 <= T) & (T < 3.75e-1));
t8 = ((3.75e-1 <= T) & (T < 5.0e-1));
t9 = ((T < 6.25e-1) & (5.0e-1 <= T));
t10 = ((6.25e-1 <= T) & (T < 7.5e-1));
t11 = ((7.5e-1 <= T) & (T < 8.75e-1));
t12 = ((8.75e-1 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t10,t11,t12,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-1.500156171440425+3.125325357167552e-2;
elseif (t3)
    out1 = T.*4.500468514321275-3.437857892884307e-1;
elseif (t4)
    out1 = T.*-1.650171788584467e+1+2.281487510732313;
elseif (t5)
    out1 = T.*6.150640302905742e+1-1.234503516081183e+1;
elseif (t6)
    out1 = T.*-1.224503106955508e+2+3.364414327034023e+1;
elseif (t7)
    out1 = T.*1.070740891486432e+2-3.808223168097042e+1;
elseif (t8)
    out1 = T.*-2.100294482087952e+1+9.946656057600622;
elseif (t9)
    out1 = T.*5.628240115399087-3.368936410538681;
elseif (t10)
    out1 = T.*-1.510015640716828+1.092473437033766;
elseif (t11)
    out1 = T.*4.118224474682259e-1-3.489051291050247e-1;
elseif (t12)
    out1 = T.*-1.372741491560753e-1+1.315543929412388e-1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
