function out1 = FGKSF1_1D5_M_5(T)
%FGKSF1_1D5_M_5
%    OUT1 = FGKSF1_1D5_M_5(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.0./3.0) & (2.0./2.7e+1 <= T));
t4 = ((T < 2.6e+1./2.7e+1) & (2.0./3.0 <= T));
t5 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T.*(-3.370614033231513);
et2 = 8.322503785722535e-2;
et3 = T.*8.953193525792986e-1;
et4 = -2.327700277583903e-1;
et5 = T.*(-6.659303419842391);
et6 = 4.80364515385607;
et7 = T.*2.748923000444845e+2;
et8 = -2.663201211451254e+2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et1+et2;
elseif (t3)
    out1 = et3+et4;
elseif (t4)
    out1 = et5+et6;
elseif (t5)
    out1 = et7+et8;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
