function out1 = FGKSF1_1D5_M_7(T)
%FGKSF1_1D5_M_7
%    OUT1 = FGKSF1_1D5_M_7(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((T < 4.6e+1./8.1e+1) & (2.6e+1./2.43e+2 <= T));
t5 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t6 = ((T < 2.6e+1./2.7e+1) & (2.0./3.0 <= T));
t7 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T;
et2 = 1.060595013569739e+2;
et3 = et1.*et2;
et4 = -2.618753119920971;
et5 = T;
et6 = -2.026686807966006e+2;
et7 = et5.*et6;
et8 = 2.025000111367714e+1;
et9 = T;
et10 = 4.535276630578224;
et11 = et9.*et10;
et12 = -1.919969639848165;
et13 = T;
et14 = -7.63959276711591;
et15 = et13.*et14;
et16 = 4.994153721805293;
et17 = T;
et18 = 4.864160188791384e-1;
et19 = et17.*et18;
et20 = -4.231854688580719e-1;
et21 = T;
et22 = -1.831213247479957;
et23 = et21.*et22;
et24 = 1.808605676524761;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
