function out1 = FGKSF1_1D5_M_6(T)
%FGKSF1_1D5_M_6
%    OUT1 = FGKSF1_1D5_M_6(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 4.6e+1./8.1e+1) & (2.0./2.7e+1 <= T));
t4 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t5 = ((T < 2.6e+1./2.7e+1) & (2.0./3.0 <= T));
t6 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T.*2.214396090961308e+1;
et2 = -5.467644669039338e-1;
et3 = T.*(-6.104417795396241);
et4 = 1.545708029763423;
et5 = T.*4.194006882100635e+1;
et6 = -2.573881523387262e+1;
et7 = T.*(-1.092369500229316e+1);
et8 = 9.503693981660389;
et9 = T.*4.112449883232742e+1;
et10 = -4.061678897019646e+1;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et1+et2;
elseif (t3)
    out1 = et3+et4;
elseif (t4)
    out1 = et5+et6;
elseif (t5)
    out1 = et7+et8;
elseif (t6)
    out1 = et9+et10;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
