function out1 = FGKSF1_1D5_M_14(T)
%FGKSF1_1D5_M_14
%    OUT1 = FGKSF1_1D5_M_14(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:09

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((2.6e+1./2.43e+2 <= T) & (T < 1.655235482395976e-1));
t5 = ((T < 1.42e+2./7.29e+2) & (1.655235482395976e-1 <= T));
t6 = ((T < 3.34e+2./7.29e+2) & (1.42e+2./7.29e+2 <= T));
t7 = ((T < 1.22e+2./2.43e+2) & (3.34e+2./7.29e+2 <= T));
t8 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t9 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t10 = ((2.0./3.0 <= T) & (T < 5.26e+2./7.29e+2));
t11 = ((T < 2.18e+2./2.43e+2) & (5.26e+2./7.29e+2 <= T));
t12 = ((T < 2.6e+1./2.7e+1) & (2.18e+2./2.43e+2 <= T));
t13 = ((2.6e+1./2.7e+1 <= T) & (T < 7.18e+2./7.29e+2));
t14 = ((T <= 1.0) & (7.18e+2./7.29e+2 <= T));
et1 = T;
et2 = -1.260692315429276e+1;
et3 = et1.*et2;
et4 = 3.112820531937048e-1;
et5 = T;
et6 = 1.205537026626844e+2;
et7 = et5.*et6;
et8 = -9.552468007323118;
et9 = T;
et10 = -1.551035278801354e+2;
et11 = et9.*et10;
et12 = 1.994172126886336e+1;
et13 = T;
et14 = 2.452223642070585e+2;
et15 = et13.*et14;
et16 = -4.632164084159124e+1;
et17 = T;
et18 = -7.872097711979801;
et19 = et17.*et18;
et20 = 2.977966281184403;
et21 = T;
et22 = 1.739221840363856e+1;
et23 = et21.*et22;
et24 = -8.597179922679155;
et25 = T;
et26 = -2.500101413338815;
et27 = et25.*et26;
et28 = 1.389910685021422;
et29 = T;
et30 = 4.025310204842214e-1;
et31 = et29.*et30;
et32 = -2.584978576435124e-1;
et33 = T;
et34 = -2.046784176692371e-1;
et35 = et33.*et34;
et36 = 1.463084344587932e-1;
et37 = T;
et38 = 1.083508389974883e-2;
et39 = et37.*et38;
et40 = -9.192391090296735e-3;
et41 = T;
et42 = -1.115487740268976e-2;
et43 = et41.*et42;
et44 = 1.05352285143601e-2;
et45 = T;
et46 = 1.251286375346872e-2;
et47 = et45.*et46;
et48 = -1.225592963601473e-2;
et49 = T;
et50 = -6.772292379767778e-3;
et51 = et49.*et50;
et52 = 6.738229628270328e-3;
if ~all(cellfun(@isscalar,{T,t10,t11,t12,t13,t14,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (t9)
    out1 = et31+et32;
elseif (t10)
    out1 = et35+et36;
elseif (t11)
    out1 = et39+et40;
elseif (t12)
    out1 = et43+et44;
elseif (t13)
    out1 = et47+et48;
elseif (t14)
    out1 = et51+et52;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
