function out1 = FGKSF1_1D5_M_13(T)
%FGKSF1_1D5_M_13
%    OUT1 = FGKSF1_1D5_M_13(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:09

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((2.6e+1./2.43e+2 <= T) & (T < 1.42e+2./7.29e+2));
t5 = ((T < 3.34e+2./7.29e+2) & (1.42e+2./7.29e+2 <= T));
t6 = ((T < 1.22e+2./2.43e+2) & (3.34e+2./7.29e+2 <= T));
t7 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t8 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t9 = ((2.0./3.0 <= T) & (T < 5.26e+2./7.29e+2));
t10 = ((T < 2.18e+2./2.43e+2) & (5.26e+2./7.29e+2 <= T));
t11 = ((T < 2.6e+1./2.7e+1) & (2.18e+2./2.43e+2 <= T));
t12 = ((2.6e+1./2.7e+1 <= T) & (T < 7.18e+2./7.29e+2));
t13 = ((T <= 1.0) & (7.18e+2./7.29e+2 <= T));
et1 = T;
et2 = -1.152307318371486e-4;
et3 = et1.*et2;
et4 = 2.845203812293795e-6;
et5 = T;
et6 = 1.101893751692924e-3;
et7 = et5.*et6;
et8 = -8.731216533808192e-5;
et9 = T;
et10 = -1.282166782471349e-3;
et11 = et9.*et10;
et12 = 1.67772500868795e-4;
et13 = T;
et14 = 1.102568890245551e-3;
et15 = et13.*et14;
et16 = -2.967439127468427e-4;
et17 = T;
et18 = -6.001269555955308e-2;
et19 = et17.*et18;
et20 = 2.770393966233236e-2;
et21 = T;
et22 = 1.57543790676925e-1;
et23 = et21.*et22;
et24 = -8.152195054692825e-2;
et25 = T;
et26 = -3.323157729587148e-1;
et27 = et25.*et26;
et28 = 1.96669900406645e-1;
et29 = T;
et30 = 2.731249630704113;
et31 = et29.*et30;
et32 = -1.845707035368574;
et33 = T;
et34 = -2.536188145885483;
et35 = et33.*et34;
et36 = 1.954940797945731;
et37 = T;
et38 = 3.54787856034177e+1;
et39 = et37.*et38;
et40 = -3.214902742159375e+1;
et41 = T;
et42 = -4.604705141149917e+2;
et43 = et41.*et42;
et44 = 4.454317797146524e+2;
et45 = T;
et46 = 1.300233029696316e+3;
et47 = et45.*et46;
et48 = -1.288704220911574e+3;
if ~all(cellfun(@isscalar,{T,t10,t11,t12,t13,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (t9)
    out1 = et31+et32;
elseif (t10)
    out1 = et35+et36;
elseif (t11)
    out1 = et39+et40;
elseif (t12)
    out1 = et43+et44;
elseif (t13)
    out1 = et47+et48;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
