function out1 = FGKSF1_1D5_M_2(T)
%FGKSF1_1D5_M_2
%    OUT1 = FGKSF1_1D5_M_2(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((0.0 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*3.464101615137755-1.732050807568877;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
