function out1 = FGKSF1_1D5_M_3(T)
%FGKSF1_1D5_M_3
%    OUT1 = FGKSF1_1D5_M_3(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./3.0) & (0.0 <= T));
t3 = ((T <= 1.0) & (2.0./3.0 <= T));
et1 = T.*(-4.286607049870548);
et2 = 1.224744871391585;
et3 = T.*1.224744871391585e+1;
et4 = -9.797958971132682;
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et1+et2;
elseif (t3)
    out1 = et3+et4;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
