function out1 = FGKSF1_1D5_M_11(T)
%FGKSF1_1D5_M_11
%    OUT1 = FGKSF1_1D5_M_11(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:09

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((2.6e+1./2.43e+2 <= T) & (T < 1.42e+2./7.29e+2));
t5 = ((T < 3.34e+2./7.29e+2) & (1.42e+2./7.29e+2 <= T));
t6 = ((T < 1.22e+2./2.43e+2) & (3.34e+2./7.29e+2 <= T));
t7 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t8 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t9 = ((2.0./3.0 <= T) & (T < 2.18e+2./2.43e+2));
t10 = ((T < 2.6e+1./2.7e+1) & (2.18e+2./2.43e+2 <= T));
t11 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T;
et2 = 1.5805316452893;
et3 = et1.*et2;
et4 = -3.902547272233762e-2;
et5 = T;
et6 = -1.511383385876471e+1;
et7 = et5.*et6;
et8 = 1.197594194244626;
et9 = T;
et10 = 1.758650153061815e+1;
et11 = et9.*et10;
et12 = -2.301207123137902;
et13 = T;
et14 = -1.316919818568742e+1;
et15 = et13.*et14;
et16 = 3.689615043824226;
et17 = T;
et18 = 1.54915652187218e+2;
et19 = et17.*et18;
et20 = -7.332045357695821e+1;
et21 = T;
et22 = -8.19618214916332e+1;
et23 = et21.*et22;
et24 = 4.560568547168311e+1;
et25 = T;
et26 = 1.118706466206346e+1;
et27 = et25.*et26;
et28 = -7.293681973626106;
et29 = T;
et30 = -1.001846975070202;
et31 = et29.*et30;
et32 = 8.322591177963372e-1;
et33 = T;
et34 = 1.365475286840932;
et35 = et33.*et34;
et36 = -1.291511471078672;
et37 = T;
et38 = -9.473216080821821e-1;
et39 = et37.*et38;
et40 = 9.356262795880305e-1;
if ~all(cellfun(@isscalar,{T,t10,t11,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (t9)
    out1 = et31+et32;
elseif (t10)
    out1 = et35+et36;
elseif (t11)
    out1 = et39+et40;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
