function out1 = FGKSF1_1D5_M_8(T)
%FGKSF1_1D5_M_8
%    OUT1 = FGKSF1_1D5_M_8(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((T < 1.22e+2./2.43e+2) & (2.6e+1./2.43e+2 <= T));
t5 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t6 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t7 = ((T < 2.6e+1./2.7e+1) & (2.0./3.0 <= T));
t8 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T;
et2 = -4.207609372042203;
et3 = et1.*et2;
et4 = 1.038915894320489e-1;
et5 = T;
et6 = 4.02352646213556e+1;
et7 = et5.*et6;
et8 = -3.188173150819641;
et9 = T;
et10 = -7.851917559832327;
et11 = et9.*et10;
et12 = 1.956957452928862;
et13 = T;
et14 = 8.42642866923774e+1;
et15 = et13.*et14;
et16 = -4.429068418809824e+1;
et17 = T;
et18 = -4.151904214427338e+1;
et19 = et17.*et18;
et20 = 2.714182354629603e+1;
et21 = T;
et22 = 2.643534518548383;
et23 = et21.*et22;
et24 = -2.299894228918482;
et25 = T;
et26 = -9.952129952223636;
et27 = et25.*et26;
et28 = 9.829264150343463;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7,t8}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
