function out1 = FGKSF1_1D5_M_9(T)
%FGKSF1_1D5_M_9
%    OUT1 = FGKSF1_1D5_M_9(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:09

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((T < 1.22e+2./2.43e+2) & (2.6e+1./2.43e+2 <= T));
t5 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t6 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t7 = ((2.0./3.0 <= T) & (T < 2.18e+2./2.43e+2));
t8 = ((T < 2.6e+1./2.7e+1) & (2.18e+2./2.43e+2 <= T));
t9 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T;
et2 = 6.04951503282854e-2;
et3 = et1.*et2;
et4 = -1.493707414671499e-3;
et5 = T;
et6 = -5.78484875520188e-1;
et7 = et5.*et6;
et8 = 4.583814635188208e-2;
et9 = T;
et10 = 1.280795762131602e-1;
et11 = et9.*et10;
et12 = -2.976134231094529e-2;
et13 = T;
et14 = -6.405869284249824;
et15 = et13.*et14;
et16 = 3.250657427139606;
et17 = T;
et18 = 1.675715665804051e+1;
et19 = et17.*et18;
et20 = -9.9036536018154;
et21 = T;
et22 = -1.665138133049283e+1;
et23 = et21.*et22;
et24 = 1.236870505720683e+1;
et25 = T;
et26 = 1.10759714681447e+2;
et27 = et25.*et26;
et28 = -1.019342535049449e+2;
et29 = T;
et30 = -1.912916056268967e+2;
et31 = et29.*et30;
et32 = 1.889299808660527e+2;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (t9)
    out1 = et31+et32;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
