function out1 = FGKSF1_1D5_M_4(T)
%FGKSF1_1D5_M_4
%    OUT1 = FGKSF1_1D5_M_4(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:08

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.0./3.0) & (2.0./2.7e+1 <= T));
t4 = ((T <= 1.0) & (2.0./3.0 <= T));
et1 = T.*(-9.804237256505327e+1);
et2 = 6.031483057988211;
et3 = T.*2.908036474387173;
et4 = -1.446325019007377;
et5 = T.*(-2.215646837628322);
et6 = 1.96946385566962;
if ~all(cellfun(@isscalar,{T,t2,t3,t4}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et1+et2;
elseif (t3)
    out1 = et3+et4;
elseif (t4)
    out1 = et5+et6;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
