function out1 = FGKSF1_1D5_M_10(T)
%FGKSF1_1D5_M_10
%    OUT1 = FGKSF1_1D5_M_10(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-06-05 16:48:09

t2 = ((T < 2.0./2.7e+1) & (0.0 <= T));
t3 = ((T < 2.6e+1./2.43e+2) & (2.0./2.7e+1 <= T));
t4 = ((2.6e+1./2.43e+2 <= T) & (T < 1.42e+2./7.29e+2));
t5 = ((T < 1.22e+2./2.43e+2) & (1.42e+2./7.29e+2 <= T));
t6 = ((T < 4.6e+1./8.1e+1) & (1.22e+2./2.43e+2 <= T));
t7 = ((T < 2.0./3.0) & (4.6e+1./8.1e+1 <= T));
t8 = ((2.0./3.0 <= T) & (T < 2.18e+2./2.43e+2));
t9 = ((T < 2.6e+1./2.7e+1) & (2.18e+2./2.43e+2 <= T));
t10 = ((T <= 1.0) & (2.6e+1./2.7e+1 <= T));
et1 = T;
et2 = -1.597407254036111e+1;
et3 = et1.*et2;
et4 = 3.944215442008906e-1;
et5 = T;
et6 = 1.527520686728552e+2;
et7 = et5.*et6;
et8 = -1.210381113825957e+1;
et9 = T;
et10 = -7.405956850946959e+1;
et11 = et9.*et10;
et12 = 1.21641006590262e+1;
et13 = T;
et14 = 1.14639523455242e+1;
et15 = et13.*et14;
et16 = -4.494801894347074;
et17 = T;
et18 = -2.318927567736036e+1;
et19 = et17.*et18;
et20 = 1.29031150554139e+1;
et21 = T;
et22 = 3.165131298308895;
et23 = et21.*et22;
et24 = -2.063585202373582;
et25 = T;
et26 = -2.83450334180449e-1;
et27 = et25.*et26;
et28 = 2.35469219285981e-1;
et29 = T;
et30 = 3.863308828975121e-1;
et31 = et29.*et30;
et32 = -3.654044651707906e-1;
et33 = T;
et34 = -2.680235936452083e-1;
et35 = et33.*et34;
et36 = 2.64714660388866e-1;
if ~all(cellfun(@isscalar,{T,t10,t2,t3,t4,t5,t6,t7,t8,t9}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = et3+et4;
elseif (t3)
    out1 = et7+et8;
elseif (t4)
    out1 = et11+et12;
elseif (t5)
    out1 = et15+et16;
elseif (t6)
    out1 = et19+et20;
elseif (t7)
    out1 = et23+et24;
elseif (t8)
    out1 = et27+et28;
elseif (t9)
    out1 = et31+et32;
elseif (t10)
    out1 = et35+et36;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
