function out1 = GKSF3_2_M128_7(T)
%GKSF3_2_M128_7
%    OUT1 = GKSF3_2_M128_7(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 10:03:29

t2 = ((0.0 <= T) & (T < 2.5e-1));
t3 = ((T < 5.0e-1) & (2.5e-1 <= T));
t4 = ((T < 7.5e-1) & (5.0e-1 <= T));
t5 = ((7.5e-1 <= T) & (T <= 1.0));
t6 = T.^2;
t7 = T.^3;
if ~all(cellfun(@isscalar,{T,t2,t3,t4,t5}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-3.454447299751209e+1+t6.*2.644788541920185e+2-t7.*5.12826039768698e+2+8.541686204772943e-1;
elseif (t3)
    out1 = T.*1.255215366697971e+2-t6.*3.757851844772182e+2+t7.*3.408593451236176e+2-1.248466551846514e+1;
elseif (t4)
    out1 = T.*-4.930136078568257e+2+t6.*8.612851045760274e+2-t7.*4.838541809118795e+2+9.060452523597199e+1;
elseif (t5)
    out1 = T.*2.657581006773783e+3-t6.*3.339507714931452e+3+t7.*1.383164849980333e+3-6.970441284216803e+2;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
