function out1 = GKSF3_2_M128_4(T)
%GKSF3_2_M128_4
%    OUT1 = GKSF3_2_M128_4(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 10:03:28

t2 = ((0.0 <= T) & (T <= 1.0));
if ~all(cellfun(@isscalar,{T,t2}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*3.174901573277509e+1-T.^2.*7.937253933193772e+1+T.^3.*5.291502622129181e+1-2.645751311064591;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
