function out1 = GKSF3_2_M128_5(T)
%GKSF3_2_M128_5
%    OUT1 = GKSF3_2_M128_5(T)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024-08-02 10:03:28

t2 = ((0.0 <= T) & (T < 5.0e-1));
t3 = ((5.0e-1 <= T) & (T <= 1.0));
t4 = T.^2;
t5 = T.^3;
if ~all(cellfun(@isscalar,{T,t2,t3}))
    error(message('symbolic:sym:matlabFunction:ConditionsMustBeScalar'));
end
if (T < 0.0)
    out1 = 0.0;
elseif (t2)
    out1 = T.*-4.762352359916263e+1+t4.*1.74619586530263e+2-t5.*1.693280839081338e+2+2.645751311064591;
elseif (t3)
    out1 = T.*2.063686022630381e+2-t4.*3.333646651941384e+2+t5.*1.693280839081338e+2-3.968626966596886e+1;
elseif (1.0 < T)
    out1 = 0.0;
else
    out1 = NaN;
end
end
